services:
  unifi-os-test:
    image: ghcr.io/lemker/unifi-os-server:latest
    container_name: unifi-os-test
    hostname: unifi-os
    cgroup: host
    privileged: true
    restart: unless-stopped
    stop_grace_period: 2m
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    extra_hosts:
      - host.docker.internal:host-gateway
    tmpfs:
      - /run:exec
      - /run/lock
      - /tmp:exec
      - /var/lib/journal
      - /var/opt/unifi/tmp:size=64m
    environment:
      - UOS_SYSTEM_IP=${UOS_SYSTEM_IP:-unifi-os.home.arpa}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - unifi-os-persistent:/persistent
      - unifi-os-var-log:/var/log
      - unifi-os-data:/data
      - unifi-os-srv:/srv
      - unifi-os-var-lib-unifi:/var/lib/unifi
      - unifi-os-var-lib-mongodb:/var/lib/mongodb
      - unifi-os-etc-rabbitmq-ssl:/etc/rabbitmq/ssl
    ports:
      - ${UOS_HTTPS_PORT:-12443}:443/tcp
      - ${UOS_DEBUG_PORT:-15005}:5005/tcp
      - ${UOS_DISCOVERY_PORT:-19543}:9543/tcp
      - ${UOS_SPEEDTEST_PORT:-16789}:6789/tcp
      - ${UOS_INFORM_PORT:-18081}:8080/tcp
      - ${UOS_ALT_HTTPS_PORT:-18443}:8443/tcp
      - ${UOS_ALT_HTTPS_PORT_2:-18444}:8444/tcp
      - ${UOS_STUN_PORT:-3480}:3478/udp
      - ${UOS_SYSLOG_PORT:-15514}:5514/udp
      - ${UOS_DISCOVERY_PORT_UDP:-10004}:10003/udp
      - ${UOS_REMOTE_PORT:-11085}:11084/tcp
      - ${UOS_AMQP_PORT:-15671}:5671/tcp
      - ${UOS_GUEST_PORT:-18880}:8880/tcp
      - ${UOS_GUEST_PORT_2:-18881}:8881/tcp
      - ${UOS_GUEST_PORT_3:-18882}:8882/tcp

volumes:
  unifi-os-data:
  unifi-os-etc-rabbitmq-ssl:
  unifi-os-persistent:
  unifi-os-srv:
  unifi-os-var-lib-mongodb:
  unifi-os-var-lib-unifi:
  unifi-os-var-log:
