services:
  db:
    image: mongo:7
    volumes:
      - /srv/docker/unifi/db:/data/db
    networks:
      - unifi

  unifi:
    image: lscr.io/linuxserver/unifi-network-application:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_USER=unifi
      - MONGO_PASS=ChangeThisPassword
    volumes:
      - /srv/docker/unifi/config:/config
    networks:
      - proxy
      - unifi