[global]
pid_file = unifi-gateway.pid
disable_broadcast = True

[gateway]
ports = [ { "ifname": "eth0", "name": "WAN", "type": "wan", "realif": "eth0" }, { "ifname": "eth1", "name": "LAN", "type": "lan", "realif": "br-lan" } ]
lan_ip = 192.168.1.1
lan_mac = BC:24:11:C9:06:42
firmware = 4.4.18.5052168
device = UGW3
device_display = OPNSense
dhcp_lease_format = dnsmasq

[provisioned]
